### ISSUE TITLE
What about switching to localStorage?

### ISSUE THREAD

**Issue by quozd** [seegno/angular-oauth2#19]
Hello again, guys!

What do you think about switching angular-cookie to [https://github.com/grevory/angular-local-storage](angular-local-storage)? It is much more powerfull and has a fallback to cookies. I can try to implement PR if you provide some thoughts about how it should be.

**Comment by ruipenso** [comment]
@quozd We've used it in the past, but the thing is that it doesn't support secure cookies. There's currently an [open issue](https://github.com/grevory/angular-local-storage/pull/185) to add support for it.

PRs are always welcome!

**Comment by quozd** [comment]
Hmm, what about pluggable interface? Something like configurable storage provider which will support both ng-cookie and local-storage?

**Comment by ruipenso** [comment]
@quozd

You can already extend/override the `OAuthTokenProvider`, using a [decorator](https://docs.angularjs.org/api/auto/service/$provide#decorator), e.g.,

```js
function oauthConfig($provide) {
  $provide.decorator('OAuthToken', function($delegate) {
    Object.defineProperties($delegate, {
      token: {
        set: function(data) {
          // your code here...
        },
        get: function() {
          // your code here...
        },
        enumerable: true,
        configurable: true
      }
    });

    $delegate.removeToken = function() {
      // your code here...
    };

    return $delegate;
  });
}
```

Note that for the `token` you need to use `Object.defineProperties` since we're using a setter/getter.
We probably will be changing this in the future.

However, we can think about adding an *out-of-the-box* configurable storage provider. I don't have time at the moment to implement it, but as I said above... PRs are always welcome! :)
