### ISSUE TITLE
Handling 401 invalid_grant error

### ISSUE THREAD

**Issue by mfagadar** [seegno/angular-oauth2#32]
Using the ```FOSOAuthServerBundle```, I ran into the situation when my OAuth2-enabled REST API returns a ```401 invalid_grant error```. 
The ```oauthInterceptor``` implementation accepts only a ```400 invalid_grant``` error and does not handle the 401 case. As a result, the ```oauth:error``` event is not triggered.
Is there a reason ```invalid_grant``` is handled only on a 400 response and not on the 401? Would it be ok to add this case in the interceptor as well ?

Thanks,
Mihai

**Comment by mfagadar** [comment]
Right now I'm using a workaround via a custom interceptor:
```javascript
app.config(function($httpProvider) {
    function lnOAuthInterceptor($q, $rootScope, OAuthToken) {
      return {
        responseError: function(rejection) {
          if (401 === rejection.status && rejection.data && 'invalid_grant' === rejection.data.error) {
            OAuthToken.removeToken();
            $rootScope.$emit('oauth:error', rejection);
          }
          return $q.reject(rejection);
        }
      }
    }

    $httpProvider.interceptors.push( lnOAuthInterceptor );
  })
```

**Comment by mfagadar** [comment]
Now I realize there is also a ```401 access_denied``` so I guess that, in order to handle all potential cases, one would need to write a custom interceptor after all :)

**Comment by cesosag** [comment]
I have the same issue, but I see the errors are implemented in the interceptor, however I can't make it work. I'm new in Angular, any hints?

**Comment by mfagadar** [comment]
@cesosag, I followed the main page instructions under the API section to the letter and it worked from the first try. In short, you need to do the following in your ```app.js``` file:
* configure the OAuthProvider
* configure the OAuthTokenProvider (i.e. if you do not have SSL yet in your dev environment, set ```secure: false``` - never on a production server ;-) ) 
* handle the ```oauth:error```event (refer to the ```$rootScope.$on('oauth:error', function(event, rejection)``` part) in the run method of the app.

**Comment by cesosag** [comment]
@mfagadar, I had already followed those steps, but the interceptor still doesn't seem to be emiting the ```oauth:error ``` so the run method doesn't get the errors and won't handle them...

**Comment by ruipenso** [comment]
We're only sending the `oauth:error` event for the most common errors:

* { status: 400, data: { error: 'invalid_request' }
* { status: 400, data: { error: 'invalid_grant' }
* { status: 401, data: { error: 'invalid_token' }

These 3 errors were also implemented because we deal with them in some way, for example, when `invalid_request` or `invalid_token` occurs we must be sure that the `token` is removed. We're also emitting the event when `invalid_token` occurs because is a common practice to refresh the token if this appends.

As, @mfagadar pointed out, the proper way to handle other errors is to implement your custom interceptor and them do something with them as described [here](https://github.com/seegno/angular-oauth2#4-catch-oauth-errors-and-do-something-with-them-optional).
