### ISSUE TITLE
Support for custom grant_type 

### ISSUE THREAD

**Issue by mihaisee** [seegno/angular-oauth2#43]
Hi, is there a way to pass  a custom grant_type instead of using the hardcoded grant_type: 'password'?
I have some additional rules on the server and I have created a custom grant type but I can't find a way to configure that. Thanks!

**Comment by ruipenso** [comment]
Hi @mihaisee,

Right now, it's not possible to do this without overriding the provider.

But, we can do this and I think it's a nice to have.

Instead of the `data` parameter just being `{ username: 'foo', password: 'bar' }`, we can change it to accept any object and extend it with the default data.

We just need to make it extendable and remove the `username` and `password` validation.

I don't have time to this now. You can submit a PR or wait until someone have time to do it.

Thanks.

**Comment by ruipenso** [comment]
@mihaisee This can now be done using 3.1.0.

**Comment by mihaisee** [comment]
Good news! Thanks! I will check it out soon

**Comment by zazoomauro** [comment]
@ruipenso How? Where is documented?

**Comment by ruipenso** [comment]
@zazoomauro We didn't added anything to the README because we are assuming that all arguments can be override the defaults when using any of the OAuthService methods.

For this case:

```js
OAuthService.getAccessToken({
  grant_type: 'foobar'
});
```
